#!/usr/bin/env bash
# Run pre-built ITS disk image on Raspberry Pi (ARM64)
#
# This script:
#   1. Builds KLH10 natively on the Pi (ARM64)
#   2. Uses the pre-built ITS disk image from build-its-image.sh
#
# Prerequisites:
#   - Artifacts from build-its-image.sh copied to this directory
#   - Pi running 64-bit Raspberry Pi OS (Debian bookworm)
#   - Packages: build-essential git autoconf libpcap-dev
#
# Usage: ./run-its-on-pi.sh [--build-only]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
KLH10_DIR="$SCRIPT_DIR/klh10-arm64"
BUILD_ONLY="${1:-}"

# ── Step 1: Check for disk image ─────────────────────────────────────────────
if [ ! -f "$SCRIPT_DIR/rp0.dsk" ] && [ ! -f "$SCRIPT_DIR/klh10/rp0.dsk" ]; then
    echo "ERROR: No ITS disk image found."
    echo "Run build-its-image.sh on Mac first, then copy artifacts here."
    exit 1
fi

# Find the disk image
DISK_IMG=$(find "$SCRIPT_DIR" -name 'rp0.dsk' -print -quit 2>/dev/null || true)
if [ -z "$DISK_IMG" ]; then
    echo "ERROR: Cannot locate rp0.dsk"
    exit 1
fi
echo "Found disk image: $DISK_IMG"

# ── Step 2: Build KLH10 natively on ARM64 ────────────────────────────────────
if [ ! -x "$KLH10_DIR/run/kn10-ks" ]; then
    echo "=== Building KLH10 for ARM64 ==="

    # Install build dependencies if missing
    for pkg in build-essential git autoconf libpcap-dev; do
        dpkg -s "$pkg" >/dev/null 2>&1 || {
            echo "Installing $pkg..."
            sudo apt-get install -y "$pkg"
        }
    done

    # Clone KLH10 — use the PDP-10 project fork which has better portability
    if [ ! -d "$KLH10_DIR/src" ]; then
        git clone --depth=1 https://github.com/PDP-10/klh10.git "$KLH10_DIR"
    fi

    cd "$KLH10_DIR"

    # Apply ARM64 compatibility patches if needed
    # The main issues on ARM64:
    #   1. Word size assumptions (PDP-10 uses 36-bit words packed into host words)
    #   2. Some inline assembly assumes x86
    #   3. Byte order (ARM64 is little-endian, same as x86, so this is OK)

    # Configure for KS (KS10 = the smallest PDP-10, what ITS ran on)
    if [ -f configure.ac ] || [ -f Makefile.mk ]; then
        # Newer build system
        make -f Makefile.mk CONFFLAGS_USR="-DKLH10_I_CIRC=1" base-ks-its || {
            echo "Trying alternate build..."
            # Some versions use a different make target
            cd src
            ./configure --target=kn10-ks
            make
            cd ..
        }
    else
        cd src
        ./configure --target=kn10-ks 2>/dev/null || ./configure
        make
        cd ..
    fi

    echo "=== KLH10 build complete ==="
fi

KLH10_BIN=$(find "$KLH10_DIR" -name 'kn10-ks' -executable -print -quit 2>/dev/null || true)
if [ -z "$KLH10_BIN" ]; then
    # Try alternate binary name
    KLH10_BIN=$(find "$KLH10_DIR" -name 'klh10' -executable -print -quit 2>/dev/null || true)
fi

if [ -z "$KLH10_BIN" ]; then
    echo "ERROR: KLH10 binary not found after build"
    echo "Check build output above for errors"
    exit 1
fi

echo "KLH10 binary: $KLH10_BIN"

if [ "$BUILD_ONLY" = "--build-only" ]; then
    echo "Build-only mode, exiting."
    exit 0
fi

# ── Step 3: Create run directory and config ───────────────────────────────────
RUN_DIR="$SCRIPT_DIR/its-run"
mkdir -p "$RUN_DIR"

# Copy/link disk image
if [ ! -f "$RUN_DIR/rp0.dsk" ]; then
    ln -sf "$(realpath "$DISK_IMG")" "$RUN_DIR/rp0.dsk"
fi

# Generate KLH10 config if not present
# Use existing config from build artifacts if available
EXISTING_INI=$(find "$SCRIPT_DIR" -name '*.ini' -o -name 'klh10.ini' 2>/dev/null | head -1)
if [ -n "$EXISTING_INI" ] && [ -f "$EXISTING_INI" ]; then
    cp "$EXISTING_INI" "$RUN_DIR/klh10.ini"
    echo "Using config from build artifacts: $EXISTING_INI"
else
    echo "Generating minimal KLH10 config..."
    cat > "$RUN_DIR/klh10.ini" << 'INIEOF'
; KLH10 configuration for ITS on KS10
; Generated by run-its-on-pi.sh

devdef rh0 rh20 addr=01776700 br=6 vec=254
devdef rp0 rp type=rp06 ipath=rp0.dsk opath=rp0.dsk

; Network (optional — enable if setting up ARPANET)
;devdef lhdh0 lhdh addr=0764100 br=6 vec=310

; Start ITS
load rp0.dsk
go
INIEOF
fi

# ── Step 4: Run ITS ──────────────────────────────────────────────────────────
echo ""
echo "=== Starting ITS ==="
echo "Console commands:"
echo "  ^E          — enter KLH10 command mode"
echo "  quit        — exit KLH10"
echo "  :login <u>  — log in to ITS"
echo ""

cd "$RUN_DIR"
exec "$KLH10_BIN" klh10.ini
