FROM jguillaumes/simh-vaxbsd

RUN apt-get update \
    && apt-get install -y --no-install-recommends vsftpd \
    && mkdir -p /var/run/vsftpd/empty \
    && rm -rf /var/lib/apt/lists/*

COPY vax/vsftpd.conf /etc/vsftpd.conf
