"""Render the landing page (`site/index.html`) from templates and optional artifacts."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from markupsafe import Markup

from .render import make_jinja_env
from .types import Resume


@dataclass(frozen=True)
class LandingContext:  # pylint: disable=too-many-instance-attributes
    """Template context for the landing page."""

    name: str
    resume_html_path: str
    resume_pdf_path: str
    contact_fragment: str | None
    vax_log_path: str | None
    build_info_html: str | None
    build_info_css_path: str | None


def _read_optional_text(path: Path) -> str | None:
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8")
    return text.strip() or None


def _build_context(*, resume: Resume, out_dir: Path) -> LandingContext:
    """Build the landing template context.

    Args:
        resume: Raw JSON Resume dict.
        out_dir: Output directory (typically `site/`).

    Returns:
        Landing context for the template.
    """
    basics = resume.get("basics") or {}
    name = str(basics.get("name") or "Resume").strip() or "Resume"

    # Read VAX-generated HTML fragment if available
    contact_html = _read_optional_text(out_dir / "contact.html")
    # Mark as safe HTML to prevent Jinja2 from escaping it
    # Safe because HTML is generated by our own VAX program, not user input
    contact_fragment = Markup(contact_html) if contact_html else None  # noqa: S704

    vax_log = _read_optional_text(out_dir / "vax-build.log")
    vax_log_path = "/vax-build.log" if vax_log else None

    # Read build info widget if available
    build_info_html_raw = _read_optional_text(out_dir / "build-info" / "build-info.html")
    # Mark as safe HTML (generated by our own script)
    build_info_html = Markup(build_info_html_raw) if build_info_html_raw else None  # noqa: S704

    # Check if build info CSS exists
    build_info_css_exists = (out_dir / "build-info" / "build-info.css").exists()
    build_info_css_path = "/build-info/build-info.css" if build_info_css_exists else None

    return LandingContext(
        name=name,
        resume_html_path="/resume/",
        resume_pdf_path="/resume.pdf",
        contact_fragment=contact_fragment,
        vax_log_path=vax_log_path,
        build_info_html=build_info_html,
        build_info_css_path=build_info_css_path,
    )


def build_landing_page(
    *,
    resume: Resume,
    out_dir: Path,
    templates_dir: Path,
    template_name: str = "index.html.j2",
) -> Path:
    """Render the landing page to `<out_dir>/index.html`.

    Args:
        resume: Raw JSON Resume dict.
        out_dir: Output directory (typically `site/`).
        templates_dir: Directory containing the landing template.
        template_name: Template file name (default: `index.html.j2`).

    Returns:
        Path to the generated HTML file.
    """
    ctx = _build_context(resume=resume, out_dir=out_dir)

    env = make_jinja_env(templates_dir)
    template = env.get_template(template_name)
    html = template.render(**ctx.__dict__)

    out_dir.mkdir(parents=True, exist_ok=True)
    index_path = out_dir / "index.html"
    index_path.write_text(html, encoding="utf-8")
    return index_path
